server:
  port: 8080
logging:
  level:
    org:
      springframework:
        data: DEBUG
spring:
  profiles: dev
  data:
    mongodb:
      host: localhost
      authentication-database: admin
      auto-index-creation: true
      password: strongPassword
      username: root
      database: movies
      port: 27017
  devtools:
    add-properties: false
  servlet:
    multipart:
      max-file-size: 4GB
security:
  secret: secret
  expirationTime: 43200000
  tokenPrefix: Bearer
  authorizationHeader: Authorization
file:
  storage:
    dir: ./store


---
spring:
  profiles: test
  data:
    mongodb:
      host: test.domain.com
      authentication-database: admin
      auto-index-creation: true
      password: strongPassword
      username: root
      database: movies
      port: 27017
security:
  secret: secret
  expirationTime: 1000 * 60 * 60
  tokenPrefix: Bearer
  authorizationHeader: Authorization
file:
  storage:
    dir: ./store
---
spring:
  profiles: prod
  data:
    mongodb:
      host: prod.domain.com
      authentication-database: admin
      auto-index-creation: true
      password: strongPassword
      username: root
      database: movies
      port: 27017
security:
  secret: secret
  expirationTime: 1000 * 60 * 60
  tokenPrefix: Bearer
  authorizationHeader: Authorization
file:
  storage:
    dir: ./store