server:
  port: 8080

spring:
  profiles: dev
  data:
    mongodb:
      host: localhost
      authentication-database: admin
      auto-index-creation: true
      database: movies_dev
      port: 27017
    web:
      pageable:
        max-page-size: 100
  devtools:
    add-properties: false
  servlet:
    multipart:
      max-file-size: 4GB
      max-request-size: 4GB
      enabled: true
  main:
    allow-bean-definition-overriding: true
security:
  secret: secret
  expirationTime: 43200000
  tokenPrefix: Bearer
  authorizationHeader: Authorization
  issuer: movie.code.dreamer.com
  admin-secret: super
file:
  storage:
    dir: ./store
  extensions: bmp, gif, jpeg, jpg, png, svg, tif, tiff ,WEBM ,MPG  ,MP2  ,MPEG  ,MPE  ,MPV ,OGG ,MP4  ,M4P  ,M4V ,AVI  ,WMV ,MOV  ,QT ,FLV  ,SWF ,AVCHD
  images:
    extensions: bmp, gif, jpeg, jpg, png, svg, tif, tiff
roles:
  user-roles:
    - ROLE_USER
    - VIEW_USER_MOVIE
  admin-roles:
    - ROLE_ADMIN
    - CREATE_ADMIN_MOVIE
    - UPDATE_ADMIN_MOVIE
    - DELETE_ADMIN_MOVIE
    - VIEW_ALL_MOVIE
    - BLOCK_ACCOUNT
    - RESET_PASSWORD
---
spring:
  profiles: test
  data:
    mongodb:
      host: test.domain.com
      authentication-database: admin
      auto-index-creation: true
      password: strongPassword
      username: root
      database: movies
      port: 27017
    web:
      pageable:
        max-page-size: 100
  devtools:
    add-properties: false
  servlet:
    multipart:
      max-file-size: 4GB
security:
  secret: secret
  expirationTime: 43200000
  tokenPrefix: Bearer
  authorizationHeader: Authorization
file:
  storage:
    dir: ./test-store
  extensions: bmp, gif, jpeg, jpg, png, svg, tif, tiff ,WEBM ,MPG  ,MP2  ,MPEG  ,MPE  ,MPV ,OGG ,MP4  ,M4P  ,M4V ,AVI  ,WMV ,MOV  ,QT ,FLV  ,SWF ,AVCHD
roles:
  user-roles:
    - ROLE_USER
    - VIEW_USER_MOVIE
  admin-roles:
    - ROLE_ADMIN
    - CREATE_ADMIN_MOVIE
    - UPDATE_ADMIN_MOVIE
    - DELETE_ADMIN_MOVIE
    - VIEW_ALL_MOVIE
    - BLOCK_ACCOUNT
    - RESET_PASSWORD
---
spring:
  profiles: prod
  data:
    mongodb:
      host: prod.domain.com
      authentication-database: admin
      auto-index-creation: true
      password: strongPassword
      username: root
      database: movies
      port: 27017
    web:
      pageable:
        max-page-size: 100
  devtools:
    add-properties: false
  servlet:
    multipart:
      max-file-size: 4GB
security:
  secret: secret
  expirationTime: 43200000
  tokenPrefix: Bearer
  authorizationHeader: Authorization
file:
  storage:
    dir: ./prod-store
  extensions: bmp, gif, jpeg, jpg, png, svg, tif, tiff ,WEBM ,MPG  ,MP2  ,MPEG  ,MPE  ,MPV ,OGG ,MP4  ,M4P  ,M4V ,AVI  ,WMV ,MOV  ,QT ,FLV  ,SWF ,AVCHD
roles:
  user-roles:
    - ROLE_USER
    - VIEW_USER_MOVIE
  admin-roles:
    - ROLE_ADMIN
    - CREATE_ADMIN_MOVIE
    - UPDATE_ADMIN_MOVIE
    - DELETE_ADMIN_MOVIE
    - VIEW_ALL_MOVIE
    - BLOCK_ACCOUNT
    - RESET_PASSWORD